### ISSUE TITLE
Issue when specifying start_val and end_val in pad function

### ISSUE THREAD

**Issue by jsilve24** [EdwinTh/padr#13]
First off, thank your work! 

I am using package version:  ‘0.2.1’
I am having a bit of an issue when I specify both the start_val and the end_val. Padr returns just a single time-point. The zip file I attached contains the Y variable the below code refers to. This code should reproduce the issue. 

```
max.date <- max(Y$t)
min.date <- min(Y$t)
Y %>% 
  arrange(t, series) %>% 
  pad(interval="day", start_val=min.date, end_val = max.date, group="series")

```

I also tried installing version ‘0.2.1.9000’ from github and then the same code gives the following error: 

Error in int_hierarchy[necesarry_interval] : 
  invalid subscript type 'list'

Thank you!
Justin 

[padr.example.RData.zip](https://github.com/EdwinTh/padr/files/859638/padr.example.RData.zip)

**Comment by jsilve24** [comment]
It appears that the problem has to do with the end_val component. I am wondering if somewhere in the code end_val got swapped for start_val and as a result the code is trying to start the series with what should be the last timestamp. 

Just a thought.

**Comment by EdwinTh** [comment]
Thanks for filing the issue. This is most certainly a bug. I have to dive into it. What I have found so far is that is not because of the grouping, and it only occurs at POSIX, not at Dates.  It is always just the last line that is returned.

By the way, the .9000 is useless for the moment, I am currently broadening the use of the interval in both `pad` and `thicken`, many things are broken because of it.
